extends: airbnb-base
env:
  webextensions: true
rules:
  global-require: off
  arrow-body-style: off
  no-console: off
  no-param-reassign: off
  no-use-before-define: off
  no-else-return: off
  no-underscore-dangle: off
  quote-props:
    - error
    - consistent
  quotes:
    - error
    - double
  valid-jsdoc:
    - error
    - requireParamDescription: false
      requireReturnDescription: false
      requireReturn: false
      prefer:
        return: return
